function [config] = sstdr_config(configuration_name)
%SSTDR_CONFIG Configuration manager for SSTDR simulations
%
% Usage:
%   sstdr_config('default')      % Load default configuration
%   sstdr_config('sine_fast')    % Fast sine wave modulation
%   sstdr_config('unmodulated')  % Unmodulated PN sequence
%   config = sstdr_config(...)   % Return configuration structure
%
% This function sets up predefined configurations for SSTDR simulations
% and provides easy integration with Simscape models.

if nargin < 1
    configuration_name = 'default';
end

fprintf('Loading SSTDR configuration: %s\n', configuration_name);

%% Predefined Configurations
switch lower(configuration_name)
    case 'default'
        config = struct( ...
            'name', 'Default SSTDR', ...
            'pn_config', struct( ...
                'modulation', 'none', ...
                'carrier_freq', 100e3, ...
                'fs', 1e6, ...
                'interpFactor', 8, ...
                'pn_bits', 10, ...
                'polynomial', [10 3 0], ...
                'magnitude', 1 ...
            ), ...
            'correlation_config', struct( ...
                'method', 'freq', ...
                'peak_threshold', 0.1, ...
                'normalize', true, ...
                'plot_results', true ...
            ), ...
            'simulation_config', struct( ...
                'stop_time', 8.184e-3, ...  % Duration for 1023*8 samples at 1MHz
                'solver', 'ode23t', ...
                'max_step', 1e-6 ...
            ) ...
        );
        
    case 'sine_fast'
        config = struct( ...
            'name', 'Fast Sine Wave SSTDR', ...
            'pn_config', struct( ...
                'modulation', 'sine', ...
                'carrier_freq', 250e3, ...
                'fs', 2e6, ...
                'interpFactor', 4, ...
                'pn_bits', 10, ...
                'polynomial', [10 3 0], ...
                'magnitude', 1 ...
            ), ...
            'correlation_config', struct( ...
                'method', 'freq', ...
                'peak_threshold', 0.15, ...
                'normalize', true, ...
                'plot_results', true ...
            ), ...
            'simulation_config', struct( ...
                'stop_time', 2.046e-3, ...
                'solver', 'ode45', ...
                'max_step', 5e-7 ...
            ) ...
        );
        
    case 'unmodulated'
        config = struct( ...
            'name', 'Unmodulated PN SSTDR', ...
            'pn_config', struct( ...
                'modulation', 'none', ...
                'carrier_freq', 2e6, ...
                'fs', 10e6, ...
                'interpFactor', 16, ...
                'pn_bits', 10, ...
                'polynomial', [10 3 0], ...
                'magnitude', 2 ...
            ), ...
            'correlation_config', struct( ...
                'method', 'both', ...
                'peak_threshold', 0.2, ...
                'normalize', true, ...
                'plot_results', true ...
            ), ...
            'simulation_config', struct( ...
                'stop_time', 16.368e-4, ...
                'solver', 'ode23t', ...
                'max_step', 1e-7 ...
            ) ...
        );
        
    case 'high_res'
        config = struct( ...
            'name', 'High Resolution SSTDR', ...
            'pn_config', struct( ...
                'modulation', 'sine', ...
                'carrier_freq', 100e3, ...
                'fs', 5e6, ...
                'interpFactor', 32, ...
                'pn_bits', 11, ...
                'polynomial', [11 2 0], ...
                'magnitude', 1 ...
            ), ...
            'correlation_config', struct( ...
                'method', 'freq', ...
                'peak_threshold', 0.05, ...
                'normalize', true, ...
                'plot_results', true ...
            ), ...
            'simulation_config', struct( ...
                'stop_time', 131.04e-3, ...
                'solver', 'ode45', ...
                'max_step', 2e-7 ...
            ) ...
        );
        
    otherwise
        error('Unknown configuration: %s. Available: default, sine_fast, unmodulated, high_res', configuration_name);
end

%% Apply Configuration
fprintf('Applying configuration: %s\n', config.name);

% Generate PN code with specified parameters
pn_params = namedargs2cell(config.pn_config);
pn_result = gen_pn_code(pn_params{:});

% Store PN generation results in config
config.pn_result = pn_result;

% Set up simulation parameters in base workspace for Simscape
assignin('base', 'sim_stop_time', config.simulation_config.stop_time);
assignin('base', 'sim_solver', config.simulation_config.solver);
assignin('base', 'sim_max_step', config.simulation_config.max_step);

% Export sampling parameters for model configuration
assignin('base', 'sim_fs', config.pn_config.fs);              % Sampling frequency
assignin('base', 'sim_ts', 1/config.pn_config.fs);            % Sample time
assignin('base', 'sim_decimation', config.pn_config.interpFactor); % Decimation factor

% Store configuration in base workspace
assignin('base', 'sstdr_config', config);

%% Display Configuration Summary
fprintf('\n=== SSTDR Configuration Summary ===\n');
fprintf('Configuration: %s\n', config.name);
fprintf('PN Sequence:\n');
fprintf('  - Length: %d bits (%d chips)\n', config.pn_config.pn_bits, pn_result.pn_length);
fprintf('  - Modulation: %s\n', config.pn_config.modulation);
if ~strcmp(config.pn_config.modulation, 'none')
    fprintf('  - Carrier: %.1f kHz\n', config.pn_config.carrier_freq/1000);
end
fprintf('  - Sampling: %.1f kHz\n', config.pn_config.fs/1000);
fprintf('  - Duration: %.3f ms\n', pn_result.total_duration*1000);
fprintf('Correlation:\n');
fprintf('  - Method: %s\n', config.correlation_config.method);
fprintf('  - Peak threshold: %.2f\n', config.correlation_config.peak_threshold);
fprintf('Simulation:\n');
fprintf('  - Stop time: %.3f ms\n', config.simulation_config.stop_time*1000);
fprintf('  - Solver: %s\n', config.simulation_config.solver);
fprintf('  - Max step: %.1f µs\n', config.simulation_config.max_step*1e6);
fprintf('Exported Variables:\n');
fprintf('  - sim_fs: %.0f Hz (sampling frequency)\n', config.pn_config.fs);
fprintf('  - sim_ts: %.2e s (sample time)\n', 1/config.pn_config.fs);
fprintf('  - sim_decimation: %d (interpolation factor)\n', config.pn_config.interpFactor);

end 